export default [
   {
      name: 'addepar',
      logo: require('../../img/portfolio company pages/company logos/addepar.png'),
      logoHeight: '27px',
      headline: 'Reporting the way you want it',
      heroImg: require('../../img/portfolio company pages/optimized hero images/addepar-2.jpg'),
      description:
         'Addepar is a Mountain View, CA-based provider of a web-based SaaS platform for cross-asset-class portfolio monitoring and reporting for family offices, private banks, endowments, wealth advisors, and asset managers. The company ended FY’19 with $1.7T of assets on its platform up 70% from FY’18.',
      founderTitle: 'FOUNDER',
      founders: ['Joe Lonsdale'],
      founded: '2009',
      category: 'Financial tech',
      website: 'addepar.com',
      background: '#00A799',
      color: 'green',
      capitalName: 'Addepar',
      headline2: 'Helping investors make better, more informed decisions. ',
      icon: 'fintech'
   },
   {
      name: 'bolt',
      logo: require('../../img/portfolio company pages/company logos/bolt.png'),
      logoHeight: '23px',
      headline: "The world's first checkout experience platform",
      heroImg: require('../../img/portfolio company pages/optimized hero images/bolt-2.jpg'),
      description:
         'Bolt is a San Francisco, CA based eCommerce software company that optimizes the checkout experience for online retailers. The company uses its data asset and proprietary algorithms to increase sales conversion and reduce shopping cart abandonment.',
      founderTitle: 'FOUNDER',
      founders: ['Ryan Breslow'],
      founded: '2014',
      category: 'Financial tech',
      website: 'bolt.com',
      background: '#00A799',
      color: 'green',
      capitalName: 'Bolt',
      headline2: "The world's first checkout experience platform",
      icon: 'fintech'
   },
   {
      name: 'blueground',
      logo: require('../../img/portfolio company pages/company logos/blueground.png'),
      logoHeight: '21px',
      headline: 'Fully furnished apartments for monthly stays',
      heroImg: require('../../img/portfolio company pages/optimized hero images/blueground.jpg'),
      description:
         'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure.',
      founderTitle: 'FOUNDERS',
      founders: [
         'Alexandros Chatzieleftheriou',
         'Penny Papakonstantinou',
         'Andreas Nezeritis',
         'Alexis Maragkos'
      ],
      founded: '2013',
      category: 'Real estate tech',
      website: 'theblueground.com',
      background: '#F47A5D',
      color: 'salmon',
      capitalName: 'Blueground',
      headline2: 'Fully furnished apartments for monthly stays',
      icon: 'retech'
   },
   {
      name: 'icapital',
      logo: require('../../img/portfolio company pages/company logos/icapitalnetwork.png'),
      logoHeight: '30px',
      headline: 'Powering the world’s alternative investment marketplace',
      heroImg: require('../../img/portfolio company pages/optimized hero images/icapital.jpg'),
      description:
         'iCapital is a New York, NY-based developer of a financial technology platform designed to democratize alternative investments. The company offers a marketplace for alternative investments, an end-to-end administrative processing solution and a proprietary research platform with over $46B in assets on its platform.',
      founderTitle: 'FOUNDERS',
      founders: ['Nick Veronis', 'Lawrence Calcano'],
      founded: '2013',
      category: 'Financial tech',
      website: 'icapitalnetwork.com',
      background: '#00A799',
      color: 'green',
      capitalName: 'iCapital',
      headline2: 'Powering the world’s alternative investment marketplace',
      icon: 'fintech'
   },
   {
      name: 'cerebral',
      logo: require('../../img/portfolio company pages/company logos/cerebral.png'),
      logoHeight: '20px',
      headline: 'Reimagning access to mental healthcare',
      heroImg: require('../../img/portfolio company pages/optimized hero images/cerebral-2.jpg'),
      description:
         'Cerebral is a San Francisco-based mental health subscription that provides customers with access to online care and medication management for three indications:!!anxiety, depression, and insomnia. Its vision is to become a digital solution for all forms of clinical mental healthcare, including therapy and medication management.',
      founderTitle: 'FOUNDERS',
      founders: ['Kyle Robertson', 'Ho Anh'],
      founded: '2019',
      category: 'Life science tech',
      website: 'getcerebral.com',
      background: '#09B5CA',
      color: 'blue',
      capitalName: 'Cerebral',
      headline2: 'Online service for mental health',
      icon: 'lifetech'
   },
   {
      name: 'hopper',
      logo: require('../../img/portfolio company pages/company logos/hopper.png'),
      logoHeight: '25px',
      headline: 'Revolutionizing the way people book travel',
      heroImg: require('../../img/portfolio company pages/optimized hero images/hopper.jpg'),
      description:
         'Hopper is a Montreal and Boston-based mobile-only travel agent that helps consumers find the lowest flight and hotel prices. The company uses its proprietary data to recommend optimal travel dates and offer innovative “synthetic” price insurance products.',
      founderTitle: 'FOUNDERS',
      founders: ['Frederic Lalonde', 'Joost Ouwerkerk'],
      founded: '2007',
      category: 'Experience tech',
      website: 'hopper.com',
      background: '#F7941D',
      color: 'orange',
      capitalName: 'Hopper',
      headline2: 'Revolutionizing how millions of people book their travel',
      icon: 'extech'
   },
   {
      name: 'skillz',
      logo: require('../../img/portfolio company pages/company logos/skillz.png'),
      logoHeight: '20px',
      headline: 'The future of entertainment',
      heroImg: require('../../img/portfolio company pages/optimized hero images/skillz.jpg'),
      description:
         'Skillz is a San Francisco, CA based mobile game development and distribution platform. The company is democratizing game development by providing small and mid-sized game studios the tools to successfully compete with large and well-capitalized incumbents. ',
      founderTitle: 'FOUNDERS',
      founders: ['Andrew Paradise', 'Casey Chafkin'],
      founded: '2012',
      category: 'Experience tech',
      website: 'skillz.com',
      background: '#F7941D',
      color: 'orange',
      capitalName: 'Skillz',
      headline2: 'Platform for competitive mobile games',
      icon: 'extech'
   },
   {
      name: 'stubhub',
      logo: require('../../img/portfolio company pages/company logos/stubhub.png'),
      logo2: require('../../img/portfolio company pages/company logos/viagogo.png'),
      logoHeight: '40px',
      logo2Height: '26px',
      headline: 'The world’s largest ticket marketplace',
      heroImg: require('../../img/portfolio company pages/optimized hero images/stubhub.jpg'),
      description:
         'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure.',
      founderTitle: 'FOUNDERS',
      founders: ['Eric Baker, Jeff Fluhr'],
      founded: '2006',
      category: 'Experience tech',
      website: 'stubhub.com',
      background: '#F7941D',
      color: 'orange',
      capitalName: 'Stubhub/ Viagogo',
      headline2: 'The world’s largest ticket marketplace',
      icon: 'extech'
   },
   {
      name: 'sonder',
      logo: require('../../img/portfolio company pages/company logos/sonder.png'),
      logoHeight: '15.6px',
      headline: 'Building the future of hospitality',
      heroImg: require('../../img/portfolio company pages/optimized hero images/sonder-2.jpg'),
      description:
         'Based in San Francisco, CA, Sonder is the #1 global platform for short-term leases and has established itself as the 2.0 hospitality brand. The company blends the home-sharing economy with the service, safety and predictability of a hotel-like experience.',
      founderTitle: 'FOUNDER',
      founders: ['Francis Davidson'],
      founded: '2014',
      category: 'Real estate tech',
      website: 'sonder.com',
      background: '#f47a5d',
      color: 'salmon',
      capitalName: 'Sonder',
      headline2: 'Building the future of hospitality',
      icon: 'retech'
   },
   {
      name: 'zupee',
      logo: require('../../img/portfolio company pages/company logos/zupee.png'),
      logoHeight: '21px',
      headline: 'The real money gaming platform in India',
      heroImg: require('../../img/portfolio company pages/optimized hero images/zupee.jpg'),
      description:
         "Zupee, founded in Jan'18 in New Delhi, India, is a mobile gaming platform that facilitates real-money competitions. The company's first game is a trivia game that lets users compete for cash prizes.",
      founderTitle: 'FOUNDER',
      founders: ['Dilsher Malhi'],
      founded: '2018',
      category: 'Experience tech',
      website: 'zupee.in',
      background: '#F7941D',
      color: 'orange',
      capitalName: 'Zupee',
      headline2: 'Real money gaming platform in India',
      icon: 'extech'
   }
]
